# Generated by Django 4.1.3 on 2023-04-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdesc',
            name='surname',
        ),
        migrations.AlterField(
            model_name='gamephoto',
            name='photo',
            field=models.ImageField(upload_to='game_photos/'),
        ),
    ]
