# Generated by Django 4.1.3 on 2023-06-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='repo',
            field=models.CharField(default='', max_length=128),
        ),
    ]
